### PR TITLE
Fix exporting Keyboard

### PR DESCRIPTION
**Pull request by danzel**
Currently it doesn't get exported!

### CODE REVIEW

**Comment by reganlawton** [comment]
@danzel  I'll give this a test and get it merged in

**Comment by reganlawton** [comment]
@danzel can you set the version in the pachage.json as 0.3.5

**Comment by danzel** [comment]
in my PR?

**Comment by reganlawton** [comment]
Yes please


On 28 Mar. 2018 7:57 am, "Dave Leaver" <notifications@github.com> wrote:

in my PR?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/xtrinch/react-touch-screen-keyboard/pull/28#issuecomment-376672903>,
or mute the thread

**Comment by reganlawton** [comment]
Yes please @danzel

**Pull request merged**
