### PR TITLE
Uppercase after space

### PR DESCRIPTION
**Pull request by reganlawton**
@danzel I've updated the project to pass the lint test and modded the example, please check then I'll merge changes into master.

### CODE REVIEW

**Comment by danzel** [comment]
LGTM :+1:

**Comment by reganlawton** [comment]
Done @danzel

**Comment by reganlawton** [comment]
@xtrinch Can you add me as a collaborator on NPM package so I can tag this release

**Comment by xtrinch** [comment]
@reganlawton you should now be able to publish to npm

**Pull request merged**
