### PR TITLE
Add focus() function

### PR DESCRIPTION
**Pull request by danbtl**
I added a `focus()` function. With this it's possible to programmatically focus the input and show the keyboard.

### CODE REVIEW

**Comment by reganlawton** [comment]
Sorry @danbtl haven't had a chance to test this yet but it looks good I'll try get it reviewed and merged today. Then I'll tag a new release

**Comment by reganlawton** [comment]
@danbtl

While doing some testing I notices that using your doc code `ref={input => input && input.focus()}` you can render multiple components to the screen, by click multiple inputs. Is this expected?

This issue only happens when using the snippet above and doesn't cause issues with the other examples. So I can approve the PR if this is expected behavior.

Here's an image from my testing. 

screen shot 2018-06-14 at 9 27 06 am

**NOTE** I added the ref to the `Uppercase After Space` input

**Comment by danbtl** [comment]
@reganlawton Good point and thanks for your review! The `ref={input => input && input.focus()}` will automatically focus the element on render. This what I need for my use-case, but won't work well with multiple elements.

Let me improve the documentation to make this more clear. I'll see if I can also add an example.

I'll update the PR tomorrow.

**Comment by danbtl** [comment]
@reganlawton I added an example and improved the documentation a bit.

**Comment by reganlawton** [comment]
@danbtl I'll merge and get this tags and onto NPM

**Pull request merged**
