### PR TITLE
add possibility to use the input in an input-group

### PR DESCRIPTION
**Pull request by jphautin**
Following issue #46, I move the input at the top level of the component.

### CODE REVIEW

**Comment by reganlawton** [comment]
@jphautin I'll give this a review today

**Comment by reganlawton** [comment]
@jphautin did you test this with `yarn start`? The project currently uses React v15 and returning an array of elements from a component’s `render` method is a v16 feature ([see](https://reactjs.org/blog/2017/09/26/react-v16.0.html#new-render-return-types-fragments-and-strings)).

The project can be updated to React v16 to support this feature and can then be released as a new MAJOR version.

**Comment by jphautin** [comment]
Hi !

Sorry for the mistake. I was also using reactstrap that is using react@16.3.2 so it upgrade the react version.

**Comment by reganlawton** [comment]
@jphautin that change looks ok and matches the changes I had to make locally when I checked out your PR. 

I'll review and test again then tag a new minor version so it would be v0.4.0

Thanks for making the update to the PR 👍

**Comment by jphautin** [comment]
@reganlawton thanks for the version :-)

**Pull request merged**
