### PR TITLE
Add uppercaseAfterSpace option

### PR DESCRIPTION
**Pull request by danzel**
When entering names, you want to capitalise each letter after a space.

### CODE REVIEW

**Comment by reganlawton** [comment]
@danzel Possible to add this new option to `./examples`?

**Comment by danzel** [comment]
Example added. I haven't rebuilt the bundle.js as I don't have the right babel set up.

**Comment by reganlawton** [comment]
I will pull your branch and rebuild it 👍

**Comment by reganlawton** [comment]
#30 is the updated PR cont. convo there

**Pull request closed without merging**
