### PR TITLE
Add ability to add functional keys to layout

### PR DESCRIPTION
**Pull request by Donutttt**
On this branch custom layouts can be adjusted to include functional keys (shift, backspace). I added this because on certain layouts, you may need to affect where these keys are placed.

This is probably rather opinionated. I added this functionality to my fork because it is useful to me, my guess is that it'd be useful to other people.

This should not break anything that exists currently, as the default position is still to just render a button with a letter.

### CODE REVIEW

**Comment by reganlawton** [comment]
@Donutttt is the idea to then disable the current keys using the on/off props?

**Comment by Donutttt** [comment]
@reganlawton That's how I've used it; hiding the number row also gets rid of the backspace key, so this allows it to be added in. I mean you _could_ use this to have the buttons in multiple place, but I imagine that'd be rare.

**Comment by reganlawton** [comment]
@Donutttt I need you to merge the latest master changes into the branch

**Comment by reganlawton** [comment]
Once done I'll merge the changes if you ping my email your done I'll do it right away I've already tested your changes

**Comment by Donutttt** [comment]
@reganlawton Does that still need to be done? The branch is showing as merged on here. If you still need me to get the latest changes then let me know, and I can do that.

**Comment by reganarkade** [comment]
No I remembered, stupid me, that I could merge it onto master and that would close the PR. Thanks for the additional @Donutttt

**Pull request merged**
