### PR TITLE
Add SCSS file for importing into projects that need custom design

### PR DESCRIPTION
**Pull request by reganlawton**
Add SCSS file for importing into projects that need custom designs see issue  #19 "Is this possible to change the appear location?"

### CODE REVIEW

**Comment by xtrinch** [comment]
If we go this route, I don't think we should maintain a css and an scss file in the src/ folder, because then updating of the styling would have to be done in two locations. Creating the css file would then somehow have to be incorporated into the building of the lib/ folder.

**Comment by reganlawton** [comment]
@xtrinch I pushed changes yesterday SCSS file is now primary and then builds a CSS file. Users can import the SCSS file and customise or copy directly and assign existing variables.

**Comment by xtrinch** [comment]
We're still missing sass-loader for example project

**Comment by xtrinch** [comment]
This one's good to go, would probably be nice to update the readme a bit, but I'm merging it right now

**Pull request merged**
