### PR TITLE
Eslint refactor

### PR DESCRIPTION
**Pull request by reganlawton**
The major work here was as follows:

* Refactoring code to fix ESLint errors, which included PropTypes & DefaultProps, etc
* Defaulting inputs to uppercase
* Updating examples with to show uppercase first changes and also support for the email field type to force to lowercase if an email field
* Added headings to examples

I've tested using the example page but additional testing would be handy.

### CODE REVIEW

**Comment by xtrinch** [comment]
Looks great, releasing.

**Comment by reganlawton** [comment]
Let me know when a release is release for NPM 👍

**Comment by xtrinch** [comment]
Already released to NPM. Noticed a bit too late that you added uppercase as default, which I don't mind, but it's a change that requires someone that is updating the library and does not wish this, to manually add a parameter. Normally I'd be against that.

**Comment by reganlawton** [comment]
Yeah I was thinking that'd be the case but my thinking was that 9/10 uppercase first would be wanted result. Emails are normally the only time you want to force lowercase and most other cases when submitting data people like to transform and valid data.

However I'll keep in mind next time.

**Comment by xtrinch** [comment]
It's okay but probably cool if we gather such changes into a batch and release with a major version :)

**Comment by reganlawton** [comment]
Yes, giving a migration path would have been a better route.

**Pull request merged**
