### PR TITLE
Add `custom-event-polyfill` package and refactor Event to CustomEvent…

### PR DESCRIPTION
**Pull request by reganlawton**
Add `custom-event-polyfill` package and refactor Event to CustomEvent to resolve issue #2, 'Creating input event does not work in IE' by @neo6238

Seems to work fine from my end.

### CODE REVIEW

**Comment by xtrinch** [comment]
Which IE are you using? Doesn't work for my 11

**Comment by reganlawton** [comment]
I used an older version like 9 i think i was via browserstack. Might be
abit more work, Firefox has issues too might be better to resolve with a
boarder cross browser milestone.

**Comment by xtrinch** [comment]
I don't think the trouble is the library, try putting its code directly into one of the source files, it works

**Comment by reganlawton** [comment]
Sorry I forgot to commit the `require('custom-event-polyfill');` in the `./src/index.js` file.

**Comment by reganlawton** [comment]
@xtrinch That should now work for you, sorry for the delay been at the gym.

**Comment by reganlawton** [comment]
Hmm that's a good way to do it @xtrinch maybe revert my change to the index.js

**Comment by xtrinch** [comment]
I think my solution only fixes the example, yours should fix the entire problem

**Comment by xtrinch** [comment]
No harm in having both. Merge? Or you still having issues with firefox?

**Comment by reganlawton** [comment]
Nope thats good to go, Firefox issue is a larger issue

**Pull request merged**
