### PR TITLE
Prop types refactor

### PR DESCRIPTION
**Pull request by reganlawton**
@xtrinch this may need bit of testing as your release changes few seconds ago could have had some issues

### CODE REVIEW

**Comment by xtrinch** [comment]
I might've made a slight mess deleting the commit history by forcing a push from a different git repo, I could have done without that.. Sorry about that! In any case I have only refactored the structure and haven't really touched the library code, so if your changes are only within that, we're good to go.

**Comment by reganlawton** [comment]
@xtrinch my changes were just a quick refacotr of Proptypes in issue #5 I'll double check the repo merge in a moment haha

**Comment by xtrinch** [comment]
I see we have some conflicting files, I gitignored the package-lock, feel free to add it back in. I've essentially also removed any dependencies other than react-draggable and added react & react-dom as peer dependencies, so people don't end up with two versions of react because of this lib.

**Comment by reganlawton** [comment]
I'll rebuild and deploy again I also ignored the ./dist folder

**Comment by xtrinch** [comment]
There is no more dist folder, and to be honest I don't know where it was being used anyway, if you have some clarity on that, I'm interested. As far as I can see, only the lib folder is used when published.

Also I've done some googling and it seems package-lock.json is not publishable and so consequently it will not do much for the end developer developing its own application and merely using the library.

**Comment by reganlawton** [comment]
@xtrinch the example seems to be broken atm? when you hit a key its just de-focusing?

**Comment by reganlawton** [comment]
Seems to work in Chrome -.-

**Comment by xtrinch** [comment]
Which browser doesn't it work in?

**Comment by reganlawton** [comment]
FirefoxDeveloperEdition 57.0b11 (64-bit) MacOS is my current.

I jsut added a change to make example testing easier

**Comment by xtrinch** [comment]
Alright I'm merging this, I see the example really does hide the keyboard upon any button click in Firefox. Will have to investigate further, help much appreaciated :)

**Comment by reganlawton** [comment]
@xtrinch those conflicts now sorted

**Pull request merged**
